<a href="https://colab.research.google.com/github/subodh2708/PYTHON/blob/main/Assignment_Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u> Use only those concepts which have been taught till now </u>

In [1]:
import numpy as np

# <u>**Problem 1**</u>

### Construct a 2-D $10*10$ matrix with the following constraints:

*  ####  The element at $[0,0]$ should be 1
*  ####   The element at $[0,9]$ should be 100
* ####   The element at $[9,0]$ should be 50
* ####   The interval between elements in rows should be constant
* ####   The interval between elements in columns should be constant



In [4]:
# Your code here

rows = np.linspace(1,50,10)
lists = []
for step in rows:
  lists.append(np.linspace(step,step*100,10,endpoint = True,dtype='int'))

array = np.array(lists)
array

array([[   1,   12,   23,   34,   45,   56,   67,   78,   89,  100],
       [   6,   77,  148,  219,  290,  360,  431,  502,  573,  644],
       [  11,  142,  273,  404,  535,  665,  796,  927, 1058, 1188],
       [  17,  208,  398,  589,  780,  970, 1161, 1352, 1542, 1733],
       [  22,  273,  523,  774, 1025, 1275, 1526, 1776, 2027, 2277],
       [  28,  338,  649,  959, 1270, 1580, 1890, 2201, 2511, 2822],
       [  33,  404,  774, 1144, 1515, 1885, 2255, 2626, 2996, 3366],
       [  39,  469,  899, 1329, 1760, 2190, 2620, 3050, 3480, 3911],
       [  44,  534, 1024, 1514, 2005, 2495, 2985, 3475, 3965, 4455],
       [  50,  600, 1150, 1700, 2250, 2800, 3350, 3900, 4450, 5000]])

#<u>**Problem 2**</u>

### Construct a 2-D $10*10$ matrix with the diagonal elements equal to zero and all the other elements equal to 1

In [6]:
# Your code below:       # Hint : Use nested for loops 
x = np.ones((10,10),dtype = 'int')

for i in range(len(x)):
  for j in range(len(x[i])):
    if i == j:
      x[i,j] = 0
print(x)      







[[0 1 1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1]
 [1 1 1 1 1 0 1 1 1 1]
 [1 1 1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 0 1 1]
 [1 1 1 1 1 1 1 1 0 1]
 [1 1 1 1 1 1 1 1 1 0]]


# <u>**Problem 3**</u>

### Construct a list of first 100 natural numbers.Create a two dimensional array with 10 rows and whose each row contains 10 columns and each number in this array is the square of the number from your constructed list. 

### For example : [[1,4,9,...,100],[121,144,...],......,]

In [ ]:
# Your code below ..







#<u>**Problem 4**</u>

### You are given an image below. Experiment with the numpy slice operation to only get the face of the person in the image

In [ ]:
 # Importing data from the skimage library. Don't worry much about it
 from skimage import data
 camera = data.camera()

In [ ]:
# Camera is 2-D array object
camera.shape

In [ ]:
camera

In [ ]:
# You can plot the camera object and see the image
import matplotlib.pyplot as plt
plt.imshow(camera)

In [ ]:
# Perform your slice operation here to get the face of the person
camera_slice = 
plt.imshow(camera_slice)