<a href="https://colab.research.google.com/github/subodh2708/practice/blob/main/practice_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import numpy as np

In [3]:
one_d_array = np.array([1,2,3,4])

In [4]:
one_d_array

array([1, 2, 3, 4])

In [5]:
two_d_array = np.array([[1,2],[3,4]])

In [6]:
two_d_array

array([[1, 2],
       [3, 4]])

In [7]:
threeD_array = np.array([[[1,2,3],[1,3,5],[3,4,5]],
                         [[5,6,7],[3,5,6],[7,8,9]]])

In [8]:
print(threeD_array)
print(threeD_array.shape)

[[[1 2 3]
  [1 3 5]
  [3 4 5]]

 [[5 6 7]
  [3 5 6]
  [7 8 9]]]
(2, 3, 3)


In [17]:
fourD_array = np.array([[[[1,2],[3,4]],
                         [[5,6],[7,8]]],
                        [[[9,10],[11,12]],
                        [[13,14],[15,16]]],
                        [[[1,2],[3,4]],
                        [[2,3],[4,5]]]])
                       
                         

In [18]:
print(fourD_array)
print(fourD_array.shape)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]


 [[[ 1  2]
   [ 3  4]]

  [[ 2  3]
   [ 4  5]]]]
(3, 2, 2, 2)


In [19]:
fourD_array.shape

(3, 2, 2, 2)

In [20]:
fourD_array.ndim

4

In [21]:
fourD_array.size

24

In [22]:
fourD_array.dtype

dtype('int64')

In [26]:
fourD_array.astype(int)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]],


       [[[ 1,  2],
         [ 3,  4]],

        [[ 2,  3],
         [ 4,  5]]]])

memory check


In [53]:
import sys

S = [0,1,2,3,4,5,6,7,8,9] 
print(sys.getsizeof(S))
print(sys.getsizeof(S)* len(S))

D= np.array([0,1,2,3,4,5,6,7,8,9])
print(D.itemsize)
print(D.size * D.itemsize)

152
1520
8
80


In [43]:
import numpy as np
import time


time check

In [52]:
size = 100000000

list1 = range(size)
list2 = range(size)

inititial = time.time()

result = [a*b for a,b in zip(list1,list2)]

time_taken = time.time() - inititial

print("time taken for list", time_taken)

one= np.arange(size)
two = np.arange(size)

inititial = time.time()

result1 = one * two

time_taken = time.time() - inititial

print("time taken for array", time_taken)

time taken for list 21.273250579833984
time taken for array 1.540050983428955
